# Generated by Django 4.0.5 on 2023-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.CharField(default='no city', max_length=512),
        ),
        migrations.AddField(
            model_name='todo',
            name='tourist_spot',
            field=models.CharField(default='no tourist spot', max_length=512),
        ),
        migrations.AddField(
            model_name='todo',
            name='url_image',
            field=models.URLField(default='no url image', max_length=255),
        ),
    ]
