# Generated by Django 4.0.5 on 2023-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todo_city_todo_tourist_spot_todo_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
