# Generated by Django 4.0.5 on 2023-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_activitylog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='like',
        ),
        migrations.AddField(
            model_name='todo',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
